version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:

    - SPRINGDOC_SWAGGER_UI_PATH
    - SPRING_API_DOCS_PATH
    - SPRING_JPA_HIBERNATE_DDL_AUTO
    - SPRING_JPA_SHOW_SQL
    - SPRING_JPA_OPEN_IN_VIEW
    - OPENTRACING_JAEGER_ENABLE
    - OPENTRACING_JAEGER_SERVICE_NAME
    - OPENTRACING_JAEGER_UDP_SENDER_HOST
    - OPENTRACING_JAEGER_UDP_SENDER_PORT
    - OPENTRACING_JAEGER_LOG_SPANS
    - SPRING_DATASOURCE_URL
    - SPRING_DATASOURCE_DRIVERCLASSNAME
    - SPRING_DATASOURCE_USERNAME
    - SPRING_DATASOURCE_PASSWORD
    - SPRING_JPA_DATABASE_PLATFORM
    - SPRING_H2_CONSOLE_ENABLED
    - SPRING_APPLICATION_NAME
